# docker-compose overrides
# overrides and extends the values in ladder99/services/docker-compose.yaml

# see other client repos for ideas for adding information to services.
# typically, would add 'profiles: - base' to each service used.
# that way, we know what is needed, and can start them all with
#   l99 start,
# which runs the base profile by default.

# version must be a string - need 3.8 for profiles
version: '3.8'

services:
  adapter:
    build: ./adapter # use ladder99/services/adapter/Dockerfile - must run 'l99 start --offline'
    profiles:
      - base

  agent:
    profiles:
      - base
    # command: agent debug agent.cfg

    # dozzle:
    #   profiles:
    #     - base

    # grafana:
    #   profiles:
    #     - base

    # meter:
    #   profiles:
    #     - base

  mosquitto:
    profiles:
      - base

  # portainer:
  #   profiles:
  #     - base

  # postgres:
  #   profiles:
  #     - base

  # pgadmin:
  #   profiles:
  #     - base

  relay:
    build: ./relay # use ladder99/services/relay/Dockerfile - must run 'l99 start --offline'
    #   profiles:
    #     - base

    # simulation:
    #   profiles:
    #     - base

    # simulator:
    #   profiles:
    #     - base
